#!/usr/bin/env ruby
APP_PATH = File.expand_path("./config/application", __dir__)
require_relative "./config/boot"
require "rails/commands"

create_table "users", id: :string, force: :cascade do |t|
  t.string   "name",    null: false
  t.string   "email",   null: false
  t.datetime "created_at", null: false, default: -> { "CURRENT_TIMESTAMP" }
  t.datetime "updated_at", null: false, default: -> { "CURRENT_TIMESTAMP" }
end

create_table "works", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
  t.string   "title",          null: false
  t.string   "description",    null: false
  t.string   "tech_stack",     null: false
  t.string   "screenshot_url", null: false
  t.string   "site_url",       null: false
  t.string   "github_url",     null: false
  t.date     "released_on",    null: false
  t.boolean  "is_published",   null: false, default: false
  t.string   "user_id",        null: false
  t.datetime "created_at",     null: false, default: -> { "CURRENT_TIMESTAMP" }
  t.datetime "updated_at",     null: false, default: -> { "CURRENT_TIMESTAMP" }
end

add_index "works", [ "user_id" ], name: "index_works_on_user_id"

add_foreign_key "works", "users", column: "user_id"
