default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
